FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

COPY ["Empresa.Api/Empresa.Api.csproj", "Empresa.Api/"]
COPY ["Empresa.Application/Empresa.Application.csproj", "Empresa.Application/"]
COPY ["Empresa.Domain/Empresa.Domain.csproj", "Empresa.Domain/"]
COPY ["Empresa.Infrastructure/Empresa.Infrastructure.csproj", "Empresa.Infrastructure/"]

RUN dotnet restore "Empresa.Api/Empresa.Api.csproj"

COPY . .

WORKDIR "/src/Empresa.Api"
RUN dotnet build "Empresa.Api.csproj" -c Release -o /app/build
RUN dotnet publish "Empresa.Api.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS runtime
WORKDIR /app

ENV ASPNETCORE_URLS=http://+:80

COPY --from=build /app/publish .

EXPOSE 8080

ENTRYPOINT ["dotnet", "Empresa.Api.dll"]
