trigger:
  branches:
    include:
      - main
      - andre-dev

pr:
  branches:
    include:
      - main
      - andre-dev

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: Release

steps:
  - task: UseDotNet@2
    displayName: "Install .NET SDK 8.x"
    inputs:
      packageType: sdk
      version: "8.0.x"

  - task: UseDotNet@2
    displayName: "Install .NET SDK 9.x"
    inputs:
      packageType: sdk
      version: "9.0.x"

  - task: DotNetCoreCLI@2
    displayName: "Restore API"
    inputs:
      command: restore
      projects: "Empresa.Api/Empresa.Api.csproj"

  - task: DotNetCoreCLI@2
    displayName: "Restore WebApp"
    inputs:
      command: restore
      projects: "Empresa.WebApp/Empresa.WebApp.csproj"

  - task: DotNetCoreCLI@2
    displayName: "Build API"
    inputs:
      command: build
      projects: "Empresa.Api/Empresa.Api.csproj"
      arguments: "--configuration $(buildConfiguration) --no-restore"

  - task: DotNetCoreCLI@2
    displayName: "Build WebApp"
    inputs:
      command: build
      projects: "Empresa.WebApp/Empresa.WebApp.csproj"
      arguments: "--configuration $(buildConfiguration) --no-restore"

  - task: DotNetCoreCLI@2
    displayName: "Publish API"
    inputs:
      command: publish
      publishWebProjects: false
      projects: "Empresa.Api/Empresa.Api.csproj"
      arguments: "--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)/api --no-build"
      zipAfterPublish: true

  - task: DotNetCoreCLI@2
    displayName: "Publish WebApp"
    inputs:
      command: publish
      publishWebProjects: false
      projects: "Empresa.WebApp/Empresa.WebApp.csproj"
      arguments: "--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)/webapp --no-build"
      zipAfterPublish: true

  - task: PublishBuildArtifacts@1
    displayName: "Publish Artifact: drop"
    inputs:
      PathtoPublish: "$(Build.ArtifactStagingDirectory)"
      ArtifactName: "drop"
      publishLocation: "Container"